In [1]:
import os
current_directory = r'C:/aa_sem_i/SOP/temat_1/dane_wejsciowe'
os.chdir(current_directory)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import mpmath

In [2]:
R = 6371000
ro = np.pi/180

In [3]:
wsp_pow = np.loadtxt('wsp_pow.txt')
f,l = wsp_pow[:,0]+wsp_pow[:,1]/60+wsp_pow[:,2]/3600, wsp_pow[:,3]+wsp_pow[:,4]/60+wsp_pow[:,5]/3600
p0 = np.array([f[0],l[0]])
f0_rad, l0_rad = np.radians(p0)
f, l = f[1:],l[1:]
f_rad, l_rad = f*ro, l*ro

In [4]:
X = R*np.cos(f_rad)*np.cos(l_rad)
Y = R*np.cos(f_rad)*np.sin(l_rad)
Z = R*np.sin(f_rad)
X,Y,Z

(array([3445768.53203705, 3451004.13847705, 3457376.5137754 ,
        3451858.58816121, 3452679.23678304, 3443418.16506686,
        3435366.06743807, 3428774.72092856, 3422107.06446313,
        3435211.50618445]),
 array([1387499.82407236, 1393362.08672747, 1396987.77346137,
        1405925.54288774, 1412860.57283002, 1425098.03329274,
        1430571.59727711, 1439251.20546833, 1437955.23150672,
        1411257.09300785]),
 array([5176018.20532177, 5170952.86494518, 5165715.22664517,
        5166980.41947069, 5164539.87201471, 5167359.86128243,
        5171205.45789462, 5173171.25955436, 5177944.47551671,
        5176612.43722311]))

In [9]:
a = np.arctan2(np.sin(l_rad-l0_rad), np.tan(f_rad)*np.cos(f0_rad) - np.cos(l_rad-l0_rad)*np.sin(f0_rad))
d = np.arcsin(np.sin(l_rad-l0_rad)*np.cos(f_rad)/np.sin(a))
d*R

array([ 87339.0734808 ,  84413.36244829,  80167.73204352,  90201.09949344,
        93747.37952641, 109253.47084189, 119388.99403325, 130381.83936842,
       135188.30047605, 108405.48128115])

In [6]:
'''h = np.arcsin(np.sin(l_rad-l0_rad)*np.cos(f_rad))
g = mpmath.acot(np.cos(l_rad-l0_rad)*(1/np.tan(f_rad)))
g*R
h*R'''

'h = np.arcsin(np.sin(l_rad-l0_rad)*np.cos(f_rad))\ng = mpmath.acot(np.cos(l_rad-l0_rad)*(1/np.tan(f_rad)))\ng*R\nh*R'